// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DeleteLocalFile(arg1) {
  return window['go']['main']['App']['DeleteLocalFile'](arg1);
}

export function GetClientState() {
  return window['go']['main']['App']['GetClientState']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function LocalFiles() {
  return window['go']['main']['App']['LocalFiles']();
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function SaveSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3, arg4);
}

export function StartSync(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartSync'](arg1, arg2, arg3, arg4);
}

export function StopSync() {
  return window['go']['main']['App']['StopSync']();
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}
