// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearLogs():Promise<void>;

export function DeleteLocalFile(arg1:string):Promise<void>;

export function GetClientState():Promise<main.ClientState>;

export function GetLogs():Promise<Array<string>>;

export function LocalFiles():Promise<Array<main.FileItem>>;

export function OpenLogFile():Promise<void>;

export function PickDirectory():Promise<string>;

export function SaveSettings(arg1:string,arg2:number,arg3:string,arg4:number):Promise<main.ClientState>;

export function StartSync(arg1:string,arg2:number,arg3:string,arg4:number):Promise<main.ClientState>;

export function StopSync():Promise<main.ClientState>;

export function SyncNow():Promise<main.ClientState>;

export function TestConnection(arg1:string,arg2:number):Promise<boolean>;
