// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPort(arg1) {
  return window['go']['main']['App']['CheckPort'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DeleteUserFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteUserFile'](arg1, arg2);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetServerState() {
  return window['go']['main']['App']['GetServerState']();
}

export function IssueToken(arg1, arg2) {
  return window['go']['main']['App']['IssueToken'](arg1, arg2);
}

export function ListTokens(arg1) {
  return window['go']['main']['App']['ListTokens'](arg1);
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RevokeToken(arg1, arg2) {
  return window['go']['main']['App']['RevokeToken'](arg1, arg2);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function SetUserEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetUserEnabled'](arg1, arg2);
}

export function StartServer(arg1, arg2) {
  return window['go']['main']['App']['StartServer'](arg1, arg2);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UserFiles(arg1) {
  return window['go']['main']['App']['UserFiles'](arg1);
}
