// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckPort(arg1:number):Promise<boolean>;

export function ClearLogs():Promise<void>;

export function CreateUser(arg1:string):Promise<main.UserInfo>;

export function DeleteUser(arg1:string):Promise<void>;

export function DeleteUserFile(arg1:string,arg2:string):Promise<void>;

export function GetLogs():Promise<Array<string>>;

export function GetServerState():Promise<main.ServerState>;

export function IssueToken(arg1:string,arg2:string):Promise<string>;

export function ListTokens(arg1:string):Promise<Array<main.TokenInfo>>;

export function ListUsers():Promise<Array<main.UserInfo>>;

export function OpenLogFile():Promise<void>;

export function PickDirectory():Promise<string>;

export function RevokeToken(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:number,arg2:string):Promise<main.ServerState>;

export function SetUserEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartServer(arg1:number,arg2:string):Promise<main.ServerState>;

export function StopServer():Promise<main.ServerState>;

export function UserFiles(arg1:string):Promise<Array<main.FileItem>>;
